version: '2'

services:
  mongodb:
    image: 'docker.io/bitnami/mongodb:4.4-debian-10'
    ports:
      - "27017:27017"
      - "28017:28017"
    volumes:
      - 'mongodb'
    environment:
      - AUTH=no

volumes:
  mongodb_data:
    driver: local
